# Generated by Django 3.2 on 2021-09-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarksDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='Enter First Name', max_length=60)),
                ('lname', models.CharField(help_text='Enter Last Name', max_length=60)),
                ('father_name', models.CharField(help_text='Enter Your Father Name', max_length=60)),
                ('course', models.CharField(help_text='Enter Course Name', max_length=60)),
                ('school_name', models.CharField(help_text='Enter School Name', max_length=60)),
                ('Telugu', models.IntegerField()),
                ('Hindi', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Mathametics', models.IntegerField()),
                ('Social', models.IntegerField()),
                ('PS', models.IntegerField(help_text='Pysical Science')),
                ('NS', models.IntegerField(help_text='Natural Science')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='Enter First Name', max_length=60)),
                ('lname', models.CharField(help_text='Enter Last Name', max_length=60)),
                ('father_name', models.CharField(help_text='Enter Your Father Name', max_length=60)),
                ('course', models.CharField(help_text='Enter Course Name', max_length=60)),
                ('school_name', models.CharField(help_text='Enter School Name', max_length=60)),
                ('roolno', models.IntegerField(help_text='Enter Rool Number')),
                ('email', models.EmailField(help_text='Enter Email', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
